### ISSUE TITLE
Question about makePrefix function

### ISSUE THREAD

**Issue by Ismael-Moreno** [rosshadden/dotfiles#2]
Hi,
Im very new to nvim and I want to replicate your directory structure. I do not understand so well what makePrefix function does.
Could you explain or give some examples on your daily use?
Thanks in advance.

**Comment by rawsp33d** [comment]
Hey!

`makePrefix` is a function I made that let's me create human-readable and nested mappings.

Here's an example:


 ```vimscript
# make the prefix
 ​call​ ​MakePrefix​(​"files​"​, ​"​<space>f​")

# use it
map <:files>t :FZF<cr>
```

It's slightly better looking and more semantically meaningful than having a bunch of mappings like `<space>ft`, which in this example would be equivalent and would be what you actually press.

It also lets me nest mappings, if that's not immediately clear. This isn't incredibly practical or beautiful, but I use it internally a bit.

```vimscript
" make a new prefix which we'll nest under the above one
call MakePrefix("remote", "<:files>R")

" use this nested prefix
map <:remote>s :SomeSSHCommandOrSomething
# (instead of mapping to `<space>fRs`)
```

I thought this was clever years ago but I'm sure by now there's a better way to do what I wanted to, which is essentially to make nested/grouped mappings.

Hope that helps. Feel free to let me know if you can think of a better way to pull this off. I'm sure there are better ways now but haven't tried looking since I did when I first made this function.

**Comment by rawsp33d** [comment]
@Ismael-Moreno I spent last weekend completely rewriting my vim config in lua, after working with and evolving the same config for over a decade. I kept the concept of having "modes", but it's _much_ more straightforward this time around.

```lua
-- create mode prefix
vim.keymap.set("n", "<space>b", "<plug><buffers>", { silent = true })

-- use it
vim.keymap.set("n", "<plug><buffers>j", ":rightbelow new<cr>", { silent = true })
```

As you can see, there is no longer any function or any sort of weirdness going on here. I map a key (in this case `<space>b` to a [`<plug>` mapping](https://neovim.io/doc/user/map.html#%3CPlug%3E), and use it in mappings like `<plug><buffers>j`.
This can be seen in the wild inside most of the files in my [modules directory](https://github.com/rosshadden/dotfiles/tree/master/src/.config/nvim/lua/core/modules).

Now... technically this would have and still will work with normal vim as well. It is not using any neovim features and not using any lua features. However at the time when I first experimented in achieving modes like this it had a lot of weird side-effects, namely it meant if you were to literally type the characters `< p l u g > < b u f f` (etc.) it would do the same thing, so all of those keys in that order would be "slow" as it waits for what may or may not come next until the timeout. Most notably the `<` key.
Neovim does not have this problem. As can be seen [here](https://neovim.io/doc/user/map.html#%3CPlug%3E) and [here](https://neovim.io/doc/user/usr_41.html#using-%3CPlug%3E) they treat it special and there is no weirdness. But I have been using neovem for years as well so I definitely could have been doing this the whole time :sweat_smile:.
